<a href="https://colab.research.google.com/github/JOJUNHYUNG0818/ai/blob/%2BdeepL/tensorflow%ED%8A%9C%EB%8F%84%EB%A6%AC%EC%96%BC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
#텐서플로우 버전 보기
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.15.0


In [4]:
# 데이터 로드하기
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

11490434/11490434 [==============================] - 0s 0us/step


In [5]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10, activation='softmax')
])

model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

In [6]:
predictions = model(x_train[:1]).numpy()
predictions

array([[0.09390918, 0.06987543, 0.05768372, 0.08527511, 0.13410519,
        0.12996702, 0.10202119, 0.12358937, 0.07511604, 0.12845774]],
      dtype=float32)

In [7]:
tf.nn.softmax(predictions).numpy()

array([[0.09935801, 0.09699853, 0.09582314, 0.09850384, 0.10343316,
        0.10300602, 0.10016729, 0.10235117, 0.0975082 , 0.10285067]],
      dtype=float32)

In [8]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [9]:
loss_fn(y_train[:1], predictions).numpy()

2.2729678

In [10]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [11]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5


/usr/local/lib/python3.10/dist-packages/keras/src/backend.py:5727: UserWarning: "`sparse_categorical_crossentropy` received `from_logits=True`, but the `output` argument was produced by a Softmax activation and thus does not represent logits. Was this intended?
  output, from_logits = _get_logits(


1875/1875 [==============================] - 7s 3ms/step - loss: 0.2956 - accuracy: 0.9132
Epoch 2/5
1875/1875 [==============================] - 5s 2ms/step - loss: 0.1430 - accuracy: 0.9566
Epoch 3/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.1074 - accuracy: 0.9676
Epoch 4/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.0868 - accuracy: 0.9732
Epoch 5/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.0738 - accuracy: 0.9772


In [12]:
model.fit(x_train, y_train, epochs=5)

model.evaluate(x_test,  y_test, verbose=2)

Epoch 1/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0660 - accuracy: 0.9788
Epoch 2/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.0597 - accuracy: 0.9813
Epoch 3/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.0530 - accuracy: 0.9826
Epoch 4/5
1875/1875 [==============================] - 5s 2ms/step - loss: 0.0476 - accuracy: 0.9844
Epoch 5/5
1875/1875 [==============================] - 5s 2ms/step - loss: 0.0450 - accuracy: 0.9851
313/313 - 1s - loss: 0.0700 - accuracy: 0.9801 - 664ms/epoch - 2ms/step


[0.06997492164373398, 0.9800999760627747]

In [13]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [14]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[0.08533698, 0.08533698, 0.08533698, 0.08533863, 0.08533698,
        0.08533698, 0.08533698, 0.23196542, 0.08533698, 0.08533699],
       [0.08533681, 0.08533693, 0.23196831, 0.08533683, 0.0853368 ,
        0.08533681, 0.0853368 , 0.0853368 , 0.08533708, 0.0853368 ],
       [0.08534041, 0.23191145, 0.0853413 , 0.08534043, 0.08534081,
        0.08534055, 0.08534054, 0.0853591 , 0.08534504, 0.0853404 ],
       [0.23188254, 0.08534222, 0.08534268, 0.08534222, 0.08534222,
        0.08534238, 0.08534233, 0.0853439 , 0.08534222, 0.08537721],
       [0.08535819, 0.08535819, 0.08535837, 0.08535819, 0.23162964,
        0.08535819, 0.0853582 , 0.08536005, 0.08535819, 0.08550276]],
      dtype=float32)>